language: java
sudo: false

dist: trusty

jdk:
- oraclejdk8

before_install:
- echo "Install Zookeeper 3.5.5"
  && wget http://archive.apache.org/dist/zookeeper/zookeeper-3.5.5/apache-zookeeper-3.5.5.tar.gz
  && tar -zxf apache-zookeeper-3.5.5.tar.gz
  && mv apache-zookeeper-3.5.5/conf/zoo_sample.cfg apache-zookeeper-3.5.5/conf/zoo.cfg
  && /bin/bash apache-zookeeper-3.5.5/bin/zkServer.sh start

install:
- mvn clean install -DskipTests -B -V
- mvn test

script:
- sh ./tools/check_format.sh

after_success:
- bash <(curl -s https://codecov.io/bash)