language: java
sudo: false

jdk:
- oraclejdk8

install:

- mvn clean install -DskipTests -B -V

script:
- sh ./check_format.sh

after_success:
- mvn clean test
- bash <(curl -s https://codecov.io/bash)