# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Zookeeper
      run: echo "Install Zookeeper 3.5.4-beta"
        && wget http://archive.apache.org/dist/zookeeper/zookeeper-3.5.4-beta/zookeeper-3.5.4-beta.tar.gz
        && tar -zxf zookeeper-3.5.4-beta.tar.gz
        && mv zookeeper-3.5.4-beta/conf/zoo_sample.cfg zookeeper-3.5.4-beta/conf/zoo.cfg
        && /bin/bash zookeeper-3.5.4-beta/bin/zkServer.sh start
    - name: Build with Maven
      run: mvn clean install -DskipTests -B -V
        && sh ./tools/check_format.sh
        && mvn clean test
