# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install 
      run: ｜
        echo "Install Zookeeper 3.5.4-beta" 
        wget http://archive.apache.org/dist/zookeeper/zookeeper-3.5.4-beta/zookeeper-3.5.4-beta.tar.gz
        tar -zxf zookeeper-3.5.4-beta.tar.gz
        mv zookeeper-3.5.4-beta/conf/zoo_sample.cfg zookeeper-3.5.4-beta/conf/zoo.cfg
        /bin/bash zookeeper-3.5.4-beta/bin/zkServer.sh start
    - name: Build with Maven
      run: ｜
        mvn clean install -DskipTests -B -V
        mvn test
    - name: Check format
      run: ls -la && sh ./check_format.sh
    - name: Codecov
      uses: codecov/codecov-action@v1
